=== noonlit/m2-playground/BabaYaga/Config/etc/covens.xsd
<?xml version="1.0" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="config">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" name="covens" type="covensList"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="covensList">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" name="coven" type="coven"/>
        </xs:sequence>
        <xs:attribute name="area" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="coven">
        <xs:sequence>
            <xs:element name="name"/>
            <xs:element name="postcode"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== noonlit/m2-playground/BabaYaga/Config/etc/covens.xml
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="covens.xsd">
    <covens area="UK">
        <coven>
            <name>We Three</name>
            <postcode>999</postcode>
        </coven>
        <coven>
            <name>Nanny Ogg Will Cook</name>
            <postcode>123</postcode>
        </coven>
    </covens>
    <covens area="RO">
        <coven>
            <name>Ileana vs. Zmeii</name>
            <postcode>000</postcode>
        </coven>
    </covens>
</config>
